<%@ Page Title="Countries" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Countries.aspx.cs" Inherits="WebApplication3.Countries" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>Your application Countries page.</h3>
    <p>Use this area to provide additional information about Countries.</p>
<p>&nbsp;</p>
        <asp:Label ID="Label5" runat="server" Text="Country ID"></asp:Label>
        <asp:TextBox ID="tjobid0" runat="server"></asp:TextBox>
        </br>
        <asp:Label ID="Label6" runat="server" Text="Country Name"></asp:Label>
        <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox></br>
        <asp:Label ID="Label7" runat="server" Text="Region Id"></asp:Label>
        <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox></br>
        <asp:Button ID="Button1" runat="server" Text="Save" />
<asp:Button ID="Button2" runat="server" Text="Close" />
<br />
<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="COUNTRY_ID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
    <Columns>
        <asp:BoundField DataField="COUNTRY_ID" HeaderText="COUNTRY_ID" ReadOnly="True" SortExpression="COUNTRY_ID" />
        <asp:BoundField DataField="COUNTRY_NAME" HeaderText="COUNTRY_NAME" SortExpression="COUNTRY_NAME" />
        <asp:BoundField DataField="REGION_ID" HeaderText="REGION_ID" SortExpression="REGION_ID" />
    </Columns>
</asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString5 %>" ProviderName="<%$ ConnectionStrings:ConnectionString5.ProviderName %>" 
    
    InsertCommand="INSERT INTO &quot;COUNTRIES&quot; (&quot;COUNTRY_ID&quot;, &quot;COUNTRY_NAME&quot;, &quot;REGION_ID&quot;) VALUES (:COUNTRY_ID, :COUNTRY_NAME, :REGION_ID)"
    DeleteCommand="DELETE FROM &quot;COUNTRIES&quot; WHERE &quot;COUNTRY_ID&quot; = :original_COUNTRY_ID AND ((&quot;COUNTRY_NAME&quot; = :original_COUNTRY_NAME) OR (&quot;COUNTRY_NAME&quot; IS NULL AND :original_COUNTRY_NAME IS NULL)) AND ((&quot;REGION_ID&quot; = :original_REGION_ID) OR (&quot;REGION_ID&quot; IS NULL AND :original_REGION_ID IS NULL))"
    UpdateCommand="UPDATE &quot;COUNTRIES&quot; SET &quot;COUNTRY_NAME&quot; = :COUNTRY_NAME, &quot;REGION_ID&quot; = :REGION_ID WHERE &quot;COUNTRY_ID&quot; = :original_COUNTRY_ID AND ((&quot;COUNTRY_NAME&quot; = :original_COUNTRY_NAME) OR (&quot;COUNTRY_NAME&quot; IS NULL AND :original_COUNTRY_NAME IS NULL)) AND ((&quot;REGION_ID&quot; = :original_REGION_ID) OR (&quot;REGION_ID&quot; IS NULL AND :original_REGION_ID IS NULL))"
    SelectCommand="SELECT * FROM &quot;COUNTRIES&quot;" OnSelecting="SqlDataSource1_Selecting" ConflictDetection="CompareAllValues" OldValuesParameterFormatString="original_{0}">
    <DeleteParameters>
        <asp:Parameter Name="original_COUNTRY_ID" Type="String" />
        <asp:Parameter Name="original_COUNTRY_NAME" Type="String" />
        <asp:Parameter Name="original_REGION_ID" Type="Decimal" />
    </DeleteParameters>
    <InsertParameters>
        <asp:Parameter Name="COUNTRY_ID" Type="String" />
        <asp:Parameter Name="COUNTRY_NAME" Type="String" />
        <asp:Parameter Name="REGION_ID" Type="Decimal" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="COUNTRY_NAME" Type="String" />
        <asp:Parameter Name="REGION_ID" Type="Decimal" />
        <asp:Parameter Name="original_COUNTRY_ID" Type="String" />
        <asp:Parameter Name="original_COUNTRY_NAME" Type="String" />
        <asp:Parameter Name="original_REGION_ID" Type="Decimal" />
    </UpdateParameters>
    </asp:SqlDataSource>
<br />
<br />
</asp:Content>
