<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="WebApplication3.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>Your application description page.</h3>
    <p>Use this area to provide additional information</p>
    <p>
        <asp:Label ID="Label1" runat="server" Text="Deparetment_ID"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label2" runat="server" Text="Department_Name"></asp:Label>
&nbsp;&nbsp;
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label3" runat="server" Text="Manager_ID"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label4" runat="server" Text="Location_Id"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Button ID="Button1" runat="server" Text="Save" />
&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button2" runat="server" Text="Clear" />
    </p>
<p>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="DEPARTMENT_ID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
        <Columns>
            <asp:BoundField DataField="DEPARTMENT_ID" HeaderText="DEPARTMENT_ID" ReadOnly="True" SortExpression="DEPARTMENT_ID" />
            <asp:BoundField DataField="DEPARTMENT_NAME" HeaderText="DEPARTMENT_NAME" SortExpression="DEPARTMENT_NAME" />
            <asp:BoundField DataField="MANAGER_ID" HeaderText="MANAGER_ID" SortExpression="MANAGER_ID" />
            <asp:BoundField DataField="LOCATION_ID" HeaderText="LOCATION_ID" SortExpression="LOCATION_ID" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString11 %>" ProviderName="<%$ ConnectionStrings:ConnectionString11.ProviderName %>" 
        
        InsertCommand="INSERT INTO &quot;DEPARTMENTS&quot; (&quot;DEPARTMENT_ID&quot;, &quot;DEPARTMENT_NAME&quot;, &quot;MANAGER_ID&quot;, &quot;LOCATION_ID&quot;) VALUES (:DEPARTMENT_ID, :DEPARTMENT_NAME, :MANAGER_ID, :LOCATION_ID)"
        DeleteCommand="DELETE FROM &quot;DEPARTMENTS&quot; WHERE &quot;DEPARTMENT_ID&quot; = :original_DEPARTMENT_ID AND &quot;DEPARTMENT_NAME&quot; = :original_DEPARTMENT_NAME AND ((&quot;MANAGER_ID&quot; = :original_MANAGER_ID) OR (&quot;MANAGER_ID&quot; IS NULL AND :original_MANAGER_ID IS NULL)) AND ((&quot;LOCATION_ID&quot; = :original_LOCATION_ID) OR (&quot;LOCATION_ID&quot; IS NULL AND :original_LOCATION_ID IS NULL))"
        UpdateCommand="UPDATE &quot;DEPARTMENTS&quot; SET &quot;DEPARTMENT_NAME&quot; = :DEPARTMENT_NAME, &quot;MANAGER_ID&quot; = :MANAGER_ID, &quot;LOCATION_ID&quot; = :LOCATION_ID WHERE &quot;DEPARTMENT_ID&quot; = :original_DEPARTMENT_ID AND &quot;DEPARTMENT_NAME&quot; = :original_DEPARTMENT_NAME AND ((&quot;MANAGER_ID&quot; = :original_MANAGER_ID) OR (&quot;MANAGER_ID&quot; IS NULL AND :original_MANAGER_ID IS NULL)) AND ((&quot;LOCATION_ID&quot; = :original_LOCATION_ID) OR (&quot;LOCATION_ID&quot; IS NULL AND :original_LOCATION_ID IS NULL))"
        SelectCommand="SELECT * FROM &quot;DEPARTMENTS&quot;" ConflictDetection="CompareAllValues" OldValuesParameterFormatString="original_{0}">
        <DeleteParameters>
            <asp:Parameter Name="original_DEPARTMENT_ID" Type="Decimal" />
            <asp:Parameter Name="original_DEPARTMENT_NAME" Type="String" />
            <asp:Parameter Name="original_MANAGER_ID" Type="Decimal" />
            <asp:Parameter Name="original_LOCATION_ID" Type="Decimal" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="DEPARTMENT_ID" Type="Decimal" />
            <asp:Parameter Name="DEPARTMENT_NAME" Type="String" />
            <asp:Parameter Name="MANAGER_ID" Type="Decimal" />
            <asp:Parameter Name="LOCATION_ID" Type="Decimal" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="DEPARTMENT_NAME" Type="String" />
            <asp:Parameter Name="MANAGER_ID" Type="Decimal" />
            <asp:Parameter Name="LOCATION_ID" Type="Decimal" />
            <asp:Parameter Name="original_DEPARTMENT_ID" Type="Decimal" />
            <asp:Parameter Name="original_DEPARTMENT_NAME" Type="String" />
            <asp:Parameter Name="original_MANAGER_ID" Type="Decimal" />
            <asp:Parameter Name="original_LOCATION_ID" Type="Decimal" />
        </UpdateParameters>
    </asp:SqlDataSource>
</p>
</asp:Content>
