<%@ Page Title="Job_History" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Job_History.aspx.cs" Inherits="WebApplication3.Job_History" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>Your application description page.</h3>
    <p>Use this area to provide additional information.</p>
    <p>&nbsp;</p>
    <p>
        <asp:Label ID="Label1" runat="server" Text="Employee_ID"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label2" runat="server" Text="Start_date"></asp:Label>
&nbsp;&nbsp;
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label3" runat="server" Text="End_Date"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label4" runat="server" Text="Department_Id"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Button ID="Button1" runat="server" Text="Save" />
&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button2" runat="server" Text="Clear" />
    </p>
    <p>&nbsp;</p>
<p>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="EMPLOYEE_ID,START_DATE" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
        <Columns>
            <asp:BoundField DataField="EMPLOYEE_ID" HeaderText="EMPLOYEE_ID" ReadOnly="True" SortExpression="EMPLOYEE_ID" />
            <asp:BoundField DataField="START_DATE" HeaderText="START_DATE" ReadOnly="True" SortExpression="START_DATE" />
            <asp:BoundField DataField="END_DATE" HeaderText="END_DATE" SortExpression="END_DATE" />
            <asp:BoundField DataField="JOB_ID" HeaderText="JOB_ID" SortExpression="JOB_ID" />
            <asp:BoundField DataField="DEPARTMENT_ID" HeaderText="DEPARTMENT_ID" SortExpression="DEPARTMENT_ID" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString9 %>" ProviderName="<%$ ConnectionStrings:ConnectionString9.ProviderName %>" 
        InsertCommand="INSERT INTO &quot;JOB_HISTORY&quot; (&quot;EMPLOYEE_ID&quot;, &quot;START_DATE&quot;, &quot;END_DATE&quot;, &quot;JOB_ID&quot;, &quot;DEPARTMENT_ID&quot;) VALUES (:EMPLOYEE_ID, :START_DATE, :END_DATE, :JOB_ID, :DEPARTMENT_ID)"
        DeleteCommand="DELETE FROM &quot;JOB_HISTORY&quot; WHERE &quot;EMPLOYEE_ID&quot; = :original_EMPLOYEE_ID AND &quot;START_DATE&quot; = :original_START_DATE AND &quot;END_DATE&quot; = :original_END_DATE AND &quot;JOB_ID&quot; = :original_JOB_ID AND ((&quot;DEPARTMENT_ID&quot; = :original_DEPARTMENT_ID) OR (&quot;DEPARTMENT_ID&quot; IS NULL AND :original_DEPARTMENT_ID IS NULL))"
        UpdateCommand="UPDATE &quot;JOB_HISTORY&quot; SET &quot;END_DATE&quot; = :END_DATE, &quot;JOB_ID&quot; = :JOB_ID, &quot;DEPARTMENT_ID&quot; = :DEPARTMENT_ID WHERE &quot;EMPLOYEE_ID&quot; = :original_EMPLOYEE_ID AND &quot;START_DATE&quot; = :original_START_DATE AND &quot;END_DATE&quot; = :original_END_DATE AND &quot;JOB_ID&quot; = :original_JOB_ID AND ((&quot;DEPARTMENT_ID&quot; = :original_DEPARTMENT_ID) OR (&quot;DEPARTMENT_ID&quot; IS NULL AND :original_DEPARTMENT_ID IS NULL))"
        SelectCommand="SELECT * FROM &quot;JOB_HISTORY&quot;" ConflictDetection="CompareAllValues" OldValuesParameterFormatString="original_{0}">
        <DeleteParameters>
            <asp:Parameter Name="original_EMPLOYEE_ID" Type="Decimal" />
            <asp:Parameter Name="original_START_DATE" Type="DateTime" />
            <asp:Parameter Name="original_END_DATE" Type="DateTime" />
            <asp:Parameter Name="original_JOB_ID" Type="String" />
            <asp:Parameter Name="original_DEPARTMENT_ID" Type="Decimal" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="EMPLOYEE_ID" Type="Decimal" />
            <asp:Parameter Name="START_DATE" Type="DateTime" />
            <asp:Parameter Name="END_DATE" Type="DateTime" />
            <asp:Parameter Name="JOB_ID" Type="String" />
            <asp:Parameter Name="DEPARTMENT_ID" Type="Decimal" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="END_DATE" Type="DateTime" />
            <asp:Parameter Name="JOB_ID" Type="String" />
            <asp:Parameter Name="DEPARTMENT_ID" Type="Decimal" />
            <asp:Parameter Name="original_EMPLOYEE_ID" Type="Decimal" />
            <asp:Parameter Name="original_START_DATE" Type="DateTime" />
            <asp:Parameter Name="original_END_DATE" Type="DateTime" />
            <asp:Parameter Name="original_JOB_ID" Type="String" />
            <asp:Parameter Name="original_DEPARTMENT_ID" Type="Decimal" />
        </UpdateParameters>
    </asp:SqlDataSource>
</p>
</asp:Content>
