<%@ Page Title="Jobs" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Jobs.aspx.cs" Inherits="WebApplication3.Jobs" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>Your application Jobs page.</h3>
    <p>Use this area to provide additional information about .</p>
    <p>
        <asp:Label ID="Label1" runat="server" Text="Job Id"></asp:Label>
        <asp:TextBox ID="tjobid" runat="server"></asp:TextBox>
        </br>
        <asp:Label ID="Label2" runat="server" Text="Job Title"></asp:Label>
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox></br>
        <asp:Label ID="Label3" runat="server" Text="Min Salary"></asp:Label>
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox></br>
        <asp:Label ID="Label4" runat="server" Text="Max Salary"></asp:Label>
        <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox></br>
    </p>
    <p>
        <asp:Button ID="Button1" runat="server" Text="Save" />
        <asp:Button ID="Button2" runat="server" Text="Close" />
    </p>
    <p>
        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="JOB_ID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Width="403px">
            <Columns>
                <asp:BoundField DataField="JOB_ID" HeaderText="JOB_ID" ReadOnly="True" SortExpression="JOB_ID" />
                <asp:BoundField DataField="JOB_TITLE" HeaderText="JOB_TITLE" SortExpression="JOB_TITLE" />
                <asp:BoundField DataField="MIN_SALARY" HeaderText="MIN_SALARY" SortExpression="MIN_SALARY" />
                <asp:BoundField DataField="MAX_SALARY" HeaderText="MAX_SALARY" SortExpression="MAX_SALARY" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString3 %>" ProviderName="<%$ ConnectionStrings:ConnectionString3.ProviderName %>" SelectCommand="SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY FROM JOBS"></asp:SqlDataSource>
    </p>
    <p>
        &nbsp;</p>
</asp:Content>
