<%@ Page Title="Locations" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Locations.aspx.cs" Inherits="WebApplication3.Locations" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>Your application description page.</h3>
    <p>Use this area to provide additional information.</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>
        <asp:Label ID="Label1" runat="server" Text="Location_Id"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label2" runat="server" Text="Street_address"></asp:Label>
&nbsp;&nbsp;
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label3" runat="server" Text="Postal_Code"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label4" runat="server" Text="City"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label5" runat="server" Text="State_province"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label6" runat="server" Text="Country_Id"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
    </p>
    <p>&nbsp;</p>
    <p>
        <asp:Button ID="Button1" runat="server" Text="Save" />
&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button2" runat="server" Text="Clear" />
    </p>
    <p>&nbsp;</p>
<p>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="LOCATION_ID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
        <Columns>
            <asp:BoundField DataField="LOCATION_ID" HeaderText="LOCATION_ID" ReadOnly="True" SortExpression="LOCATION_ID" />
            <asp:BoundField DataField="STREET_ADDRESS" HeaderText="STREET_ADDRESS" SortExpression="STREET_ADDRESS" />
            <asp:BoundField DataField="POSTAL_CODE" HeaderText="POSTAL_CODE" SortExpression="POSTAL_CODE" />
            <asp:BoundField DataField="CITY" HeaderText="CITY" SortExpression="CITY" />
            <asp:BoundField DataField="STATE_PROVINCE" HeaderText="STATE_PROVINCE" SortExpression="STATE_PROVINCE" />
            <asp:BoundField DataField="COUNTRY_ID" HeaderText="COUNTRY_ID" SortExpression="COUNTRY_ID" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString8 %>" ProviderName="<%$ ConnectionStrings:ConnectionString8.ProviderName %>" 
        
        InsertCommand="INSERT INTO &quot;LOCATIONS&quot; (&quot;LOCATION_ID&quot;, &quot;STREET_ADDRESS&quot;, &quot;POSTAL_CODE&quot;, &quot;CITY&quot;, &quot;STATE_PROVINCE&quot;, &quot;COUNTRY_ID&quot;) VALUES (:LOCATION_ID, :STREET_ADDRESS, :POSTAL_CODE, :CITY, :STATE_PROVINCE, :COUNTRY_ID)"
        DeleteCommand="DELETE FROM &quot;LOCATIONS&quot; WHERE &quot;LOCATION_ID&quot; = :original_LOCATION_ID AND ((&quot;STREET_ADDRESS&quot; = :original_STREET_ADDRESS) OR (&quot;STREET_ADDRESS&quot; IS NULL AND :original_STREET_ADDRESS IS NULL)) AND ((&quot;POSTAL_CODE&quot; = :original_POSTAL_CODE) OR (&quot;POSTAL_CODE&quot; IS NULL AND :original_POSTAL_CODE IS NULL)) AND &quot;CITY&quot; = :original_CITY AND ((&quot;STATE_PROVINCE&quot; = :original_STATE_PROVINCE) OR (&quot;STATE_PROVINCE&quot; IS NULL AND :original_STATE_PROVINCE IS NULL)) AND ((&quot;COUNTRY_ID&quot; = :original_COUNTRY_ID) OR (&quot;COUNTRY_ID&quot; IS NULL AND :original_COUNTRY_ID IS NULL))"
        UpdateCommand="UPDATE &quot;LOCATIONS&quot; SET &quot;STREET_ADDRESS&quot; = :STREET_ADDRESS, &quot;POSTAL_CODE&quot; = :POSTAL_CODE, &quot;CITY&quot; = :CITY, &quot;STATE_PROVINCE&quot; = :STATE_PROVINCE, &quot;COUNTRY_ID&quot; = :COUNTRY_ID WHERE &quot;LOCATION_ID&quot; = :original_LOCATION_ID AND ((&quot;STREET_ADDRESS&quot; = :original_STREET_ADDRESS) OR (&quot;STREET_ADDRESS&quot; IS NULL AND :original_STREET_ADDRESS IS NULL)) AND ((&quot;POSTAL_CODE&quot; = :original_POSTAL_CODE) OR (&quot;POSTAL_CODE&quot; IS NULL AND :original_POSTAL_CODE IS NULL)) AND &quot;CITY&quot; = :original_CITY AND ((&quot;STATE_PROVINCE&quot; = :original_STATE_PROVINCE) OR (&quot;STATE_PROVINCE&quot; IS NULL AND :original_STATE_PROVINCE IS NULL)) AND ((&quot;COUNTRY_ID&quot; = :original_COUNTRY_ID) OR (&quot;COUNTRY_ID&quot; IS NULL AND :original_COUNTRY_ID IS NULL))"
        
        SelectCommand="SELECT * FROM &quot;LOCATIONS&quot;" ConflictDetection="CompareAllValues" OldValuesParameterFormatString="original_{0}">
        <DeleteParameters>
            <asp:Parameter Name="original_LOCATION_ID" Type="Decimal" />
            <asp:Parameter Name="original_STREET_ADDRESS" Type="String" />
            <asp:Parameter Name="original_POSTAL_CODE" Type="String" />
            <asp:Parameter Name="original_CITY" Type="String" />
            <asp:Parameter Name="original_STATE_PROVINCE" Type="String" />
            <asp:Parameter Name="original_COUNTRY_ID" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="LOCATION_ID" Type="Decimal" />
            <asp:Parameter Name="STREET_ADDRESS" Type="String" />
            <asp:Parameter Name="POSTAL_CODE" Type="String" />
            <asp:Parameter Name="CITY" Type="String" />
            <asp:Parameter Name="STATE_PROVINCE" Type="String" />
            <asp:Parameter Name="COUNTRY_ID" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="STREET_ADDRESS" Type="String" />
            <asp:Parameter Name="POSTAL_CODE" Type="String" />
            <asp:Parameter Name="CITY" Type="String" />
            <asp:Parameter Name="STATE_PROVINCE" Type="String" />
            <asp:Parameter Name="COUNTRY_ID" Type="String" />
            <asp:Parameter Name="original_LOCATION_ID" Type="Decimal" />
            <asp:Parameter Name="original_STREET_ADDRESS" Type="String" />
            <asp:Parameter Name="original_POSTAL_CODE" Type="String" />
            <asp:Parameter Name="original_CITY" Type="String" />
            <asp:Parameter Name="original_STATE_PROVINCE" Type="String" />
            <asp:Parameter Name="original_COUNTRY_ID" Type="String" />
        </UpdateParameters>
    </asp:SqlDataSource>
</p>
</asp:Content>
